/**
 * Blender codec — headless `--background --python` (priority 2).
 *
 * Declared CLI surface (Blender 3.x/4.x):
 *   blender --background --python gen_render.py -- project.json <outdir>
 * The native project artifact is a Gen JSON bundle (edit model + blender
 * extensions). The generated script drives bpy: VSE movie strips for
 * tracks/clips, keyframed fcurves for animation, the clip tracker for
 * editor.track-object, scene.render for output. The tracking op writes a
 * tracking.json artifact reporting what the headless run actually achieved —
 * never fabricated data (lock P5). .blend materialization happens inside the
 * blender run when the binary is present; without it, render fails with
 * binary-missing (never a GUI workaround).
 */

import type { EditorCommand, RenderProfile } from "../../contract.js";
import type { EditProject } from "../edit/edit-model.js";
import { applyCreateAnimation } from "../edit/apply.js";
import { createAnimationParamsSchema, parseKeyframes, parseTuple, trackObjectParamsSchema, validateCommandParams } from "../edit/commands.js";
import type { ApplyResult, CodecEnv, CodecState, EditorCapabilityMapping, NativeProjectCodec, ParseResult, RenderPlanResult, SourceAssetMeta } from "../edit/codec.js";
import { failure } from "../edit/codec.js";
import type { OtioFidelity } from "../otio/parse.js";

export const BLENDER_FIDELITY: OtioFidelity = {
  preserved: ["track count/order (VSE channels)", "clip source in/out", "clip record placement", "animation curves (fcurves)"],
  lossy: [
    { feature: "sub-frame timing", rule: "quantized to whole frames at scene fps" },
    { feature: "layer transform", rule: "VSE strip transform carries offset/scale; rotation maps to strip rotation in degrees" },
  ],
  dropped: ["tracking ops are blender-native extensions (OTIO export carries clip ranges only)"],
};

export const BLENDER_CAPABILITIES: readonly EditorCapabilityMapping[] = [
  { capabilityId: "editor.create-animation", maturity: "experimental", modeNotes: "cli — generated bpy script inserts keyframes (scene fps grid)" },
  { capabilityId: "editor.composite-layer", maturity: "experimental", modeNotes: "cli — VSE channels with ALPHAOVER blend + blend_alpha" },
  { capabilityId: "editor.render-project", maturity: "experimental", modeNotes: "cli — bpy.ops.render.render(animation=True) via generated script" },
  { capabilityId: "editor.track-object", maturity: "experimental", modeNotes: "cli — movie clip tracker markers via generated script (headless op coverage unverified in sandbox)" },
];

export interface BlenderTrackingOp {
  readonly targetLabel: string;
  readonly regionX: number;
  readonly regionY: number;
  readonly regionW: number;
  readonly regionH: number;
  readonly start: number;
  readonly end: number;
  readonly assetId: string;
}

export function buildBlenderScript(): string {
  return [
    "# Generated by @gen/editor-adapters — Blender headless render driver.",
    "import json, os, sys",
    "argv = sys.argv[sys.argv.index('--') + 1:]",
    "project_path, out_dir = argv[0], argv[1]",
    "with open(project_path) as fh:",
    "    project = json.load(fh)",
    "edit, render_cfg = project['edit'], project.get('render', {})",
    "import bpy",
    "scene = bpy.context.scene",
    "scene.render.fps = int(edit['fps'])",
    "scene.render.resolution_x = int(edit['resolution']['width'])",
    "scene.render.resolution_y = int(edit['resolution']['height'])",
    "end_s = max([clip['recordStart'] + clip['sourceDuration'] for track in edit['tracks'] for clip in track['clips']] or [0])",
    "scene.frame_start = 1",
    "scene.frame_end = max(1, int(round(end_s * edit['fps'])))",
    "seq = scene.sequence_editor_create()",
    "for ti, track in enumerate(edit['tracks']):",
    "    channel = ti + 1",
    "    for clip in track['clips']:",
    "        start_f = int(round(clip['recordStart'] * edit['fps'])) + 1",
    "        end_f = int(round((clip['recordStart'] + clip['sourceDuration']) * edit['fps'])) + 1",
    "        strip = seq.sequences.new_movie(name=clip['name'], filepath=clip['assetPath'], channel=channel, frame_start=start_f)",
    "        strip.frame_final_start = start_f",
    "        strip.frame_final_end = end_f",
    "        if ti > 0:",
    "            strip.blend_type = 'ALPHAOVER'",
    "            strip.blend_alpha = float(clip.get('opacity', 1.0))",
    "        tr = clip.get('transform')",
    "        if tr is not None:",
    "            strip.transform.offset_x = float(tr.get('x', 0))",
    "            strip.transform.offset_y = float(tr.get('y', 0))",
    "            strip.transform.scale_x = float(tr.get('scale', 1))",
    "            strip.transform.scale_y = float(tr.get('scale', 1))",
    "for curve in edit.get('animationCurves', []):",
    "    if not curve['target'].startswith('clip:'):",
    "        continue",
    "    strip = next((s for s in seq.sequences_all if s.name == curve['target'][5:]), None)",
    "    if strip is None:",
    "        continue",
    "    for key in curve['keys']:",
    "        frame = int(round(key['time'] * edit['fps'])) + 1",
    "        if curve['property'] == 'opacity':",
    "            strip.blend_alpha = float(key['value'])",
    "            strip.keyframe_insert(data_path='blend_alpha', frame=frame)",
    "tracking_report = []",
    "for op in project.get('blender', {}).get('trackingOps', []):",
    "    clip = bpy.data.movieclips.load(filepath=op['assetPath'])",
    "    track = clip.tracking.tracks.new(op['targetLabel'], 0)",
    "    frame = int(round(op['start'] * edit['fps'])) + 1",
    "    marker = track.markers.insert(frame, ((op['regionX'] + op['regionW'] / 2.0) / clip.size[0], (op['regionY'] + op['regionH'] / 2.0) / clip.size[1]))",
    "    entry = {'targetLabel': op['targetLabel'], 'seedMarkerFrame': frame, 'trackedFrames': 0, 'status': 'marker-seeded'}",
    "    try:",
    "        for area in bpy.context.window_manager.windows[0].screen.areas if bpy.context.window_manager.windows else []:",
    "            if area.type == 'CLIP_EDITOR':",
    "                override = {'area': area, 'clip': clip}",
    "                with bpy.context.temp_override(**override):",
    "                    bpy.ops.clip.track_markers(clip=clip, frame=False)",
    "                entry['trackedFrames'] = len(track.markers)",
    "                entry['status'] = 'tracked'",
    "                break",
    "    except Exception as exc:",
    "        entry['status'] = 'tracking-op-unavailable-headless: ' + str(exc)",
    "    tracking_report.append(entry)",
    "if tracking_report:",
    "    with open(os.path.join(out_dir, 'tracking.json'), 'w') as fh:",
    "        json.dump({'tracking': tracking_report}, fh, indent=2)",
    "fmt = render_cfg.get('format', 'mp4')",
    "if fmt == 'png-sequence':",
    "    scene.render.image_settings.file_format = 'PNG'",
    "    scene.render.filepath = os.path.join(out_dir, 'frame#####.png')",
    "else:",
    "    scene.render.image_settings.file_format = 'FFMPEG'",
    "    scene.render.ffmpeg.format = 'MPEG4'",
    "    scene.render.ffmpeg.codec = 'H264'",
    "    scene.render.filepath = os.path.join(out_dir, 'frames0001.mp4')",
    "bpy.ops.render.render(animation=True)",
  ].join("\n");
}

function blenderBundle(state: CodecState, env: CodecEnv, render?: { format: string }): string {
  const edit = state.project;
  const tracks = edit.tracks.map((track, index) => ({
    name: track.name,
    kind: track.kind,
    clips: track.clips.map((clip) => ({
      name: clip.name,
      assetId: clip.assetId,
      assetPath: env.assetPathOf(clip.assetId) ?? clip.assetPath ?? clip.assetId,
      sourceStart: clip.sourceRange.start.value / clip.sourceRange.start.rate,
      sourceDuration: clip.sourceRange.duration.value / clip.sourceRange.duration.rate,
      recordStart: clip.recordRange.start.value / clip.recordRange.start.rate,
      opacity: clip.opacity ?? (index > 0 ? 1 : undefined),
      transform:
        clip.transform === undefined
          ? undefined
          : { x: clip.transform.x, y: clip.transform.y, scale: clip.transform.scale, rotation: clip.transform.rotation },
    })),
  }));
  const bundle: Record<string, unknown> = {
    kind: "gen.blender-project",
    version: 1,
    edit: {
      name: edit.name,
      fps: edit.fps,
      resolution: edit.resolution,
      tracks,
      animationCurves: edit.animationCurves,
      markers: edit.markers,
    },
    blender: state.extensions ?? {},
  };
  if (render !== undefined) bundle.render = render;
  return `${JSON.stringify(bundle, null, 2)}\n`;
}

export function parseBlenderBundle(content: string): ParseResult {
  try {
    const parsed: unknown = JSON.parse(content);
    if (typeof parsed !== "object" || parsed === null) return { ok: false, issues: ["bundle root must be an object"] };
    const bundle = parsed as { kind?: string; edit?: Record<string, unknown>; blender?: Record<string, unknown> };
    if (bundle.kind !== "gen.blender-project") return { ok: false, issues: ["not a gen.blender-project bundle"] };
    const edit = bundle.edit;
    if (edit === undefined || !Array.isArray(edit.tracks)) return { ok: false, issues: ["missing edit.tracks"] };
    const tracks = (edit.tracks as Record<string, unknown>[]).map((track) => ({
      kind: track.kind === "audio" ? ("audio" as const) : ("video" as const),
      name: String(track.name ?? ""),
      clips: ((track.clips as Record<string, unknown>[]) ?? []).map((clip) => ({
        name: String(clip.name ?? "clip"),
        assetId: String(clip.assetId ?? "art.unresolved"),
        sourceRange: { start: { value: Number(clip.sourceStart ?? 0), rate: 1 }, duration: { value: Number(clip.sourceDuration ?? 0), rate: 1 } },
        recordRange: { start: { value: Number(clip.recordStart ?? 0), rate: 1 }, duration: { value: Number(clip.sourceDuration ?? 0), rate: 1 } },
        opacity: clip.opacity === undefined ? undefined : Number(clip.opacity),
      })),
    }));
    const resolution = (edit.resolution as Record<string, unknown> | undefined) ?? {};
    const project: EditProject = {
      name: String(edit.name ?? "blender-project"),
      fps: Number(edit.fps ?? 25),
      resolution: { width: Number(resolution.width ?? 1280), height: Number(resolution.height ?? 720) },
      tracks,
      animationCurves: (Array.isArray(edit.animationCurves) ? edit.animationCurves : []) as EditProject["animationCurves"],
      markers: (Array.isArray(edit.markers) ? edit.markers : []) as EditProject["markers"],
    };
    return { ok: true, state: { project, extensions: bundle.blender } };
  } catch (error) {
    return { ok: false, issues: [`invalid JSON: ${String(error)}`] };
  }
}

export function createBlenderCodec(): NativeProjectCodec {
  return {
    editorId: "blender",
    fileExtension: "json",
    nativeMediaType: "application/vnd.gen.blender-project+json",
    servedCapabilities: BLENDER_CAPABILITIES,
    fidelity: BLENDER_FIDELITY,
    projectFromAsset(asset: SourceAssetMeta & { path: string }): CodecState {
      return {
        project: {
          name: `blender-${asset.artifactId}`,
          fps: asset.fps,
          resolution: { width: asset.width, height: asset.height },
          tracks: [
            {
              kind: "video",
              name: "V1",
              clips: [
                {
                  name: "clip-0",
                  assetId: asset.artifactId,
                  assetPath: asset.path,
                  sourceRange: { start: { value: 0, rate: 1 }, duration: { value: asset.durationSeconds, rate: 1 } },
                  recordRange: { start: { value: 0, rate: 1 }, duration: { value: asset.durationSeconds, rate: 1 } },
                },
              ],
            },
          ],
          animationCurves: [],
          markers: [],
        },
      };
    },
    applyCommand(state: CodecState, command: EditorCommand, env: CodecEnv): ApplyResult {
      const validated = validateCommandParams(command.capabilityId, command.params);
      if (!validated.ok) return failure("validation", "bad-params", validated.issues.join("; "));
      if (command.capabilityId === "editor.create-animation") {
        return applyCreateAnimation(state, createAnimationParamsSchema.parse(command.params));
      }
      if (command.capabilityId === "editor.track-object") {
        const params = trackObjectParamsSchema.parse(command.params);
        const [x, y, w, h] = parseTuple(params.region, 4);
        const assetId = state.project.tracks[0]?.clips[0]?.assetId ?? "";
        const assetPath = env.assetPathOf(assetId);
        if (assetPath === undefined) {
          return failure("validation", "bad-artifact", "tracking target asset is not materialized");
        }
        const extensions = (state.extensions ?? {}) as { trackingOps?: BlenderTrackingOp[] };
        const op: BlenderTrackingOp = {
          targetLabel: params.targetLabel,
          regionX: x ?? 0,
          regionY: y ?? 0,
          regionW: w ?? 0,
          regionH: h ?? 0,
          start: params.start,
          end: params.end ?? params.start,
          assetId,
        };
        return {
          ok: true,
          state: { ...state, extensions: { ...extensions, trackingOps: [...(extensions.trackingOps ?? []), op] } },
        };
      }
      return failure("unsupported", "capability-not-served", `blender adapter does not serve ${command.capabilityId}`);
    },
    serialize: (state: CodecState, env: CodecEnv): string => blenderBundle(state, env),
    parse: parseBlenderBundle,
    renderPlan(state: CodecState, profile: RenderProfile, env: CodecEnv): RenderPlanResult {
      if (profile.format !== "mp4" && profile.format !== "png-sequence") {
        return { ok: false, reason: "unsupported-profile", message: `blender render supports mp4/png-sequence, got ${profile.format}` };
      }
      const output = profile.format === "png-sequence" ? "render/frame00001.png" : "render/frames0001.mp4";
      return {
        ok: true,
        plan: {
          command: "blender",
          args: ["--background", "--python", "gen_render.py", "--", "project.rCURRENT.json", "render"],
          outputRelativePath: output,
          supportFiles: [
            { relativePath: "gen_render.py", content: buildBlenderScript() },
            { relativePath: "project.rCURRENT.json", content: blenderBundle(state, env, { format: profile.format }) },
          ],
        },
      };
    },
  };
}

/** Test helper: keyframe times from a "t=v;…" spec. */
export function blenderKeyframeTimes(spec: string): readonly number[] {
  return parseKeyframes(spec).map((key) => key.time);
}
