/**
 * Natron codec — CLI (priority 4).
 *
 * Declared surface (Natron 2.x Python API, executed by `NatronRenderer` —
 * the headless render binary — or `natron -b`):
 *   NatronRenderer gen_render.py
 * The script runs with the `app` object predefined and builds:
 *   Read(asset) → [Transform] → Merge(mix) → Write(output)
 * then app.render(write, first, last) and app.saveProject(path).
 * Plugin ids targeted: fr.inria.openfx.ReadFFmpeg /
 * net.sf.openfx.MergePlugin / net.sf.openfx.TransformPlugin /
 * fr.inria.openfx.WriteFFmpeg (verified live on Natron 2.4.4; the legacy
 * fr.inria.natron.* ids return None from createNode).
 * The sandbox has no Natron binary: this codec implements the declared
 * contract and its live conformance is recorded as skipped/unverified —
 * never claimed (lock P5, work order §3 environment note).
 */

import type { EditorCommand, RenderProfile } from "../../contract.js";
import type { EditProject } from "../edit/edit-model.js";
import { applyCompositeLayer } from "../edit/apply.js";
import { compositeLayerParamsSchema, validateCommandParams } from "../edit/commands.js";
import type { ApplyResult, CodecEnv, CodecState, EditorCapabilityMapping, NativeProjectCodec, ParseResult, RenderPlanResult, SourceAssetMeta } from "../edit/codec.js";
import { failure } from "../edit/codec.js";
import type { OtioFidelity } from "../otio/parse.js";

export const NATRON_FIDELITY: OtioFidelity = {
  preserved: ["layer stack order (Read→Merge chain)", "clip source in/out (frame range)", "layer opacity (Merge mix)"],
  lossy: [{ feature: "layer transform", rule: "x/y/scale map to the Transform node; rotation maps to Natron's Transform rotate parameter (degrees)" }],
  dropped: ["multi-track record placement beyond the composite stack (Natron node graph is layer-oriented, not timeline-oriented)", "gen animation curves (declared out of the launch subset)"],
};

export const NATRON_CAPABILITIES: readonly EditorCapabilityMapping[] = [
  { capabilityId: "editor.composite-layer", maturity: "experimental", modeNotes: "cli — NatronRenderer executes a generated Python script building Read/Merge/Write" },
];

export function buildNatronScript(): string {
  return [
    "# Generated by @gen/editor-adapters — Natron headless render driver.",
    "# Runs inside Natron/NatronRenderer with `app` predefined.",
    "import json, os, sys",
    "script_dir = os.path.dirname(os.path.abspath(sys.argv[1])) if len(sys.argv) > 1 else os.getcwd()",
    "with open(os.path.join(script_dir, 'project.rCURRENT.json')) as fh:",
    "    project = json.load(fh)",
    "edit, comp = project['edit'], project['natron']",
    "fps = float(edit['fps'])",
    "render_cfg = project.get('render', {})",
    "nodes = []",
    "def param(node, name, value):",
    "    p = node.getParam(name)",
    "    if p is not None:",
    "        p.set(value)",
    "def param_choice(node, name, value):",
    "    p = node.getParam(name)",
    "    if p is None or value is None:",
    "        return",
    "    try:",
    "        opts = p.getOptions()",
    "    except Exception:",
    "        return",
    "    if value in opts:",
    "        p.set(opts.index(value))",
    "for source in comp['sources']:",
    "    read = app.createNode('fr.inria.openfx.ReadFFmpeg')",
    "    param(read, 'filename', source['path'])",
    "    param(read, 'firstFrame', int(source['firstFrame']))",
    "    param(read, 'lastFrame', int(source['lastFrame']))",
    "    nodes.append(read)",
    "current = nodes[0] if nodes else None",
    "for layer_index, layer in enumerate(comp['layers']):",
    "    read = app.createNode('fr.inria.openfx.ReadFFmpeg')",
    "    param(read, 'filename', layer['path'])",
    "    param(read, 'firstFrame', int(layer['firstFrame']))",
    "    param(read, 'lastFrame', int(layer['lastFrame']))",
    "    if layer.get('transform') is not None:",
    "        tr = app.createNode('net.sf.openfx.TransformPlugin')",
    "        param(tr, 'translate', (layer['transform']['x'], layer['transform']['y']))",
    "        param(tr, 'scale', (layer['transform']['scale'], layer['transform']['scale']))",
    "        param(tr, 'rotate', layer['transform'].get('rotation', 0))",
    "        tr.connectInput(0, read)",
    "        layer_input = tr",
    "    else:",
    "        layer_input = read",
    "    merge = app.createNode('net.sf.openfx.MergePlugin')",
    "    param(merge, 'mix', float(layer.get('opacity', 1.0)))",
    "    merge.connectInput(0, current)",
    "    merge.connectInput(1, layer_input)",
    "    current = merge",
    "write = app.createNode('fr.inria.openfx.WriteFFmpeg')",
    "param(write, 'filename', comp['outputPath'])",
    "param(write, 'fps', fps)",
    "param_choice(write, 'format', render_cfg.get('format'))",
    "param_choice(write, 'codec', render_cfg.get('codec'))",
    "write.connectInput(0, current)",
    "app.render(write, int(comp['firstFrame']), int(comp['lastFrame']))",
    "app.saveProject(os.path.join(script_dir, 'natron.ntp'))",
  ].join("\n");
}

interface NatronLayerSpec {
  readonly path: string;
  readonly firstFrame: number;
  readonly lastFrame: number;
  readonly opacity?: number;
  readonly transform?: { readonly x: number; readonly y: number; readonly scale: number; readonly rotation: number };
}

function natronBundle(state: CodecState, env: CodecEnv, output?: string, render?: { format: string; codec?: string }): string {
  const project = state.project;
  const fps = project.fps;
  const toFrames = (seconds: number): number => Math.max(1, Math.round(seconds * fps));
  const base = project.tracks[0]?.clips[0];
  const sources =
    base === undefined
      ? []
      : [
          {
            path: env.assetPathOf(base.assetId) ?? base.assetPath ?? base.assetId,
            firstFrame: 1,
            lastFrame: toFrames(base.sourceRange.duration.value / base.sourceRange.duration.rate),
          },
        ];
  const layers: NatronLayerSpec[] = [];
  for (const track of project.tracks.slice(1)) {
    for (const clip of track.clips) {
      layers.push({
        path: env.assetPathOf(clip.assetId) ?? clip.assetPath ?? clip.assetId,
        firstFrame: 1,
        lastFrame: toFrames(clip.sourceRange.duration.value / clip.sourceRange.duration.rate),
        opacity: clip.opacity,
        transform: clip.transform,
      });
    }
  }
  const lastFrame = Math.max(
    1,
    toFrames(
      Math.max(0, ...project.tracks.flatMap((track) => track.clips.map((clip) => (clip.recordRange.start.value + clip.recordRange.duration.value) / clip.recordRange.start.rate))),
    ),
  );
  const bundle: Record<string, unknown> = {
    kind: "gen.natron-project",
    version: 1,
    edit: { name: project.name, fps, resolution: project.resolution },
    natron: { sources, layers, firstFrame: 1, lastFrame, outputPath: output ?? "render/output.mp4" },
  };
  if (render !== undefined) bundle.render = render;
  return `${JSON.stringify(bundle, null, 2)}\n`;
}

export function parseNatronBundle(content: string): ParseResult {
  try {
    const parsed: unknown = JSON.parse(content);
    if (typeof parsed !== "object" || parsed === null) return { ok: false, issues: ["bundle root must be an object"] };
    const bundle = parsed as { kind?: string; natron?: Record<string, unknown>; edit?: Record<string, unknown> };
    if (bundle.kind !== "gen.natron-project" || bundle.natron === undefined || bundle.edit === undefined) {
      return { ok: false, issues: ["not a gen.natron-project bundle"] };
    }
    const natron = bundle.natron;
    const sources = (natron.sources as Record<string, unknown>[]) ?? [];
    const layers = (natron.layers as Record<string, unknown>[]) ?? [];
    const edit = bundle.edit;
    const fps = Number(edit.fps ?? 25);
    const firstClip = sources[0];
    const clips = [
      ...(firstClip === undefined
        ? []
        : [
            {
              name: "base",
              assetId: String(firstClip.path ?? "art.unresolved"),
              sourceRange: { start: { value: 0, rate: 1 }, duration: { value: Number(firstClip.lastFrame ?? 1) / fps, rate: 1 } },
              recordRange: { start: { value: 0, rate: 1 }, duration: { value: Number(firstClip.lastFrame ?? 1) / fps, rate: 1 } },
            },
          ]),
      ...layers.map((layer, index) => ({
        name: `layer-${index}`,
        assetId: String(layer.path ?? "art.unresolved"),
        sourceRange: { start: { value: 0, rate: 1 }, duration: { value: Number(layer.lastFrame ?? 1) / fps, rate: 1 } },
        recordRange: { start: { value: 0, rate: 1 }, duration: { value: Number(layer.lastFrame ?? 1) / fps, rate: 1 } },
        opacity: layer.opacity === undefined ? undefined : Number(layer.opacity),
      })),
    ];
    const resolution = (edit.resolution as Record<string, unknown> | undefined) ?? {};
    const project: EditProject = {
      name: String(edit.name ?? "natron-project"),
      fps,
      resolution: { width: Number(resolution.width ?? 1280), height: Number(resolution.height ?? 720) },
      tracks: clips.length > 0 ? [{ kind: "video" as const, name: "V1", clips }] : [],
      animationCurves: [],
      markers: [],
    };
    return { ok: true, state: { project } };
  } catch (error) {
    return { ok: false, issues: [`invalid JSON: ${String(error)}`] };
  }
}

export function createNatronCodec(): NativeProjectCodec {
  return {
    editorId: "natron",
    fileExtension: "json",
    nativeMediaType: "application/vnd.gen.natron-project+json",
    servedCapabilities: NATRON_CAPABILITIES,
    fidelity: NATRON_FIDELITY,
    projectFromAsset(asset: SourceAssetMeta & { path: string }): CodecState {
      return {
        project: {
          name: `natron-${asset.artifactId}`,
          fps: asset.fps,
          resolution: { width: asset.width, height: asset.height },
          tracks: [
            {
              kind: "video",
              name: "V1",
              clips: [
                {
                  name: "base",
                  assetId: asset.artifactId,
                  assetPath: asset.path,
                  sourceRange: { start: { value: 0, rate: 1 }, duration: { value: asset.durationSeconds, rate: 1 } },
                  recordRange: { start: { value: 0, rate: 1 }, duration: { value: asset.durationSeconds, rate: 1 } },
                },
              ],
            },
          ],
          animationCurves: [],
          markers: [],
        },
      };
    },
    applyCommand(state: CodecState, command: EditorCommand, env: CodecEnv): ApplyResult {
      const validated = validateCommandParams(command.capabilityId, command.params);
      if (!validated.ok) return failure("validation", "bad-params", validated.issues.join("; "));
      if (command.capabilityId === "editor.composite-layer") {
        const params = compositeLayerParamsSchema.parse(command.params);
        const path = env.assetPathOf(params.layerArtifactRef);
        const meta = env.assetMetaOf(params.layerArtifactRef);
        const layerMeta = path === undefined || meta === undefined ? undefined : { path, durationSeconds: meta.durationSeconds, fps: meta.fps };
        return applyCompositeLayer(state, params, layerMeta);
      }
      return failure("unsupported", "capability-not-served", `natron adapter does not serve ${command.capabilityId}`);
    },
    serialize: natronBundle,
    parse: parseNatronBundle,
    renderPlan(state: CodecState, profile: RenderProfile, env: CodecEnv): RenderPlanResult {
      if (profile.format !== "mp4") {
        return { ok: false, reason: "unsupported-profile", message: `natron render supports mp4 (Write node), got ${profile.format}` };
      }
      const renderSpec = profile.codec === undefined ? { format: profile.format } : { format: profile.format, codec: profile.codec };
      return {
        ok: true,
        plan: {
          command: "NatronRenderer",
          args: ["gen_render.py"],
          outputRelativePath: "render/output.mp4",
          supportFiles: [
            { relativePath: "gen_render.py", content: buildNatronScript() },
            { relativePath: "project.rCURRENT.json", content: natronBundle(state, env, "render/output.mp4", renderSpec) },
          ],
        },
      };
    },
  };
}
