/**
 * W14 method-selection provenance generation: maps the lab's committed
 * selection-ledger record (file-based handoff — arena-bridge does not import
 * @gen/agent-lab in the architecture policy) onto the Arena plane as a
 * proposal-style provenance record with REAL numbers from the REAL pipeline
 * run over the documentary-cinematic goal class, then walks the
 * draft → certified → published lifecycle and commits the example record.
 *
 * The chain is validated at generation time, never rubber-stamped: the cited
 * committed evaluation record must agree with the ledger entry (certified,
 * same aggregate fitness). Deterministic timestamps throughout — re-running
 * reproduces the committed record byte-for-byte.
 *
 * Provenance: the ledger records were generated by
 * packages/agent-lab/scripts/generate-selection-ledger.ts (real
 * evaluateAndCertify runs; the rule row is the vanilla default run whose
 * certified optimum is the committed T2 evaluation record).
 *
 * Run: node --import tsx scripts/generate-method-selection-provenance.ts
 */
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { MethodSelectionLedgerEntry } from "../src/domain/schema/method-selection-provenance.js";
import { MethodSelectionLedgerEntrySchema } from "../src/domain/schema/method-selection-provenance.js";
import type { MethodSelectionProvenanceMappingInput } from "../src/domain/method-selection-provenance.js";
import {
  certifyProvenance,
  mapSelectionToProvenance,
  publishProvenance,
} from "../src/domain/method-selection-provenance.js";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const repoRoot = join(packageRoot, "..", "..");
const provenanceDir = join(packageRoot, "src", "domain", "method-selection-provenance");

/** Deterministic lifecycle timestamps (committed evidence stays stable). */
const AT = {
  certified: "2026-10-05T09:30:00.000Z",
  published: "2026-10-05T09:45:00.000Z",
} as const;

const GOAL_CLASS = "documentary-cinematic-remaster";
const METHOD = "rule";
const LEDGER_DIR = join(repoRoot, "packages", "agent-lab", "src", "domain", "method-selection", "records");
const EVAL_RECORD = "packages/agent-lab/src/domain/evaluations/eval.org.documentary-cinematic-remaster-cand-04.json";

interface CommittedEvaluation {
  readonly aggregateFitness: number;
  readonly certified: boolean;
  readonly recordId: string;
}

async function main(): Promise<void> {
  // 1. The committed ledger records (file-based handoff from the lab).
  const files = (await readdir(LEDGER_DIR)).filter((name) => name.startsWith("sel.") && name.endsWith(".json")).sort();
  const entries: { file: string; entry: MethodSelectionLedgerEntry }[] = [];
  for (const file of files) {
    const raw = JSON.parse(await readFile(join(LEDGER_DIR, file), "utf8")) as unknown;
    const parsed = MethodSelectionLedgerEntrySchema.safeParse(raw);
    if (!parsed.success) {
      throw new Error(`committed ledger record ${file}: schema violation (mirror drift?)`);
    }
    entries.push({ file, entry: parsed.data });
  }
  const chosen = entries.find(({ entry }) => entry.goalClass === GOAL_CLASS && entry.method === METHOD);
  if (!chosen) {
    throw new Error(`no committed ${METHOD} selection record for goal class ${GOAL_CLASS}`);
  }

  // 2. The certified evaluation the selection produced (the chain's top rung)
  //    must AGREE with the ledger entry — real numbers, validated.
  const evaluation = JSON.parse(await readFile(join(repoRoot, EVAL_RECORD), "utf8")) as CommittedEvaluation;
  if (evaluation.certified !== true || chosen.entry.certified !== true) {
    throw new Error("the cited evaluation / ledger entry did not certify — refusing to build provenance");
  }
  if (evaluation.aggregateFitness !== chosen.entry.rankedBestFitness) {
    throw new Error(
      `chain mismatch: evaluation aggregateFitness ${evaluation.aggregateFitness} != ledger rankedBestFitness ${chosen.entry.rankedBestFitness}`,
    );
  }

  // 3. Map → certify → publish (deterministic timestamps).
  const input: MethodSelectionProvenanceMappingInput = {
    entry: chosen.entry,
    evidence: {
      ledgerRecordRef: `packages/agent-lab/src/domain/method-selection/records/${chosen.file}`,
      telemetry: {
        method: chosen.entry.method,
        seed: chosen.entry.seed,
        candidatesConsidered: chosen.entry.candidatesConsidered,
        candidatesEmitted: chosen.entry.candidatesEmitted,
        evaluationsRun: chosen.entry.evaluationsRun,
      },
      certifiedEvaluationRef: EVAL_RECORD,
      certifiedFitness: chosen.entry.rankedBestFitness,
    },
    notes:
      "W14 provenance-ladder example: the vanilla rule-method pipeline run over documentary-cinematic-remaster " +
      "(search → simulate → evaluate → certify). Real numbers from the committed ledger: 32 candidates considered " +
      "and emitted, 0 internal evaluations (rule never evaluates), ranked best fitness 0.8398 — the committed T2 " +
      "certified optimum (replayHash 3474f812). On the committed ledger this row ties with the evolutionary and " +
      "bandit rows at 0.8398 and wins the learned policy's tie-break with 0 evaluationsRun.",
  };
  const mapped = mapSelectionToProvenance(input);
  if (!mapped.ok) {
    throw new Error(`provenance mapping refused the evidence: ${mapped.issues.join("; ")}`);
  }
  const certified = certifyProvenance(mapped.record, AT.certified);
  if (!certified.ok) throw new Error(certified.issue);
  const published = publishProvenance(certified.record, AT.published);
  if (!published.ok) throw new Error(published.issue);

  // 4. Commit the example record.
  await mkdir(provenanceDir, { recursive: true });
  const outPath = join(provenanceDir, `${published.record.provenanceId}.json`);
  await writeFile(outPath, `${JSON.stringify(published.record, null, 2)}\n`, "utf8");
  console.log(
    `method-selection provenance: ${published.record.provenanceId} → ${published.record.lifecycle.state} ` +
      `(method=${published.record.method}, fitness=${published.record.rankedBestFitness}, ` +
      `ledger=${published.record.evidence.ledgerRecordRef})`,
  );
}

await main();
